databaseprod:   
  dbname: db_mysql
  dbtable: music
pods:
  image: yanivomc/spring-music
food:
  drink: beer
  eat: Peanut Butter and Jelly sandwich


service:
  Name: spring-service
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 8080


deployment:
  replicas: 1
  container:
    name: spring-music
    image: yanivomc/spring-music:latest
    containerPort: 8080