databaseprod:   
  dbname: db_mysql
  dbtable: music
pods:
  image: yanivomc/spring-music
food:
  drink: beer
  eat: Peanut Butter and Jelly sandwich


service:
  Name: spring-service
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 8080


deployment:
  replicas: 3
  container:
    name: spring-music
    image: yanivomc/spring-music
    containerPort: 8080
    tag: latest

ingress:
  enabled: true

job:
 sleepyTime: 1
