apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      {{- include "spring.labels" . | nindent 6}}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "spring.labels" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.deployment.container.image }}:{{ .Values.deployment.container.tag }}
        ports:
        - containerPort: {{ .Values.deployment.container.containerPort }}
