apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.Name }}
spec:
  selector:
    app: {{ .Release.Name }}    
    {{- include "spring.labels" . | nindent 4}}
  {{ if .Values.ingress.enabled }}
  type: {{ .Values.service.type }}
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }} 
